name: NPM Release
on:
  push:
    branches:
      - main
jobs:
  npm-release:
    name: Publish
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.name "Alejandro Reyes"
      - run: git config --global user.email "arcaela.reyes@gmail.com"
      - run: npm ci
      - run: npm publish --access=public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: rm -rf ./src ./lib